platform :ios, '9.0'

target 'MeinsApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for meins
  pod 'mailcore2-ios'

  pod 'react-native-cameraroll', :path => '../node_modules/@matthiasn/cameraroll'

  target 'MeinsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
