default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    changelog = read_changelog(changelog_path: '../CHANGELOG.md')
    build_app(
      skip_build_archive: true,
      archive_path: "../build/ios/archive/Runner.xcarchive",
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      changelog: changelog,
    )
  end
end
