default_platform(:mac)

platform :mac do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore", readonly: is_ci)

    changelog = read_changelog(changelog_path: '../CHANGELOG.md')
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      changelog: changelog,
    )
  end
end
