opt_out_usage
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"

  lane :certificates do
    create_keychain(
      name: "fastlane.keychain",
      password: ENV['KEYCHAIN_PW'],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true
    )
    match(
      app_identifier: ["com.matthiasn.meins", "com.matthiasn.meinsNightly"],
      type: "development",
      readonly: true,
      keychain_name: "fastlane.keychain",
      keychain_password: ENV['KEYCHAIN_PW']
    )
    match(
      app_identifier: ["com.matthiasn.meins", "com.matthiasn.meinsNightly"],
      type: "appstore",
      readonly: true,
      keychain_name: "fastlane.keychain",
      keychain_password: ENV['KEYCHAIN_PW']
    )
  end

  lane :nightly do
    update_info_plist(
      plist_path: "meins/Info.plist",
      display_name: "meins-nightly"
    )
    build_app(
      export_method: "app-store",
      workspace: "meins.xcworkspace",
      scheme: "meinsNightly",
      export_options: {
        provisioningProfiles: {
          "com.matthiasn.meinsNightly" => "match AppStore com.matthiasn.meinsNightly"
        }
      }
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: false,
      app_identifier: "com.matthiasn.meinsNightly"
    )
    deliver(
      force: true,
      skip_metadata: true,
      skip_screenshots: true,
      skip_binary_upload: true,
      submission_information: {
          export_compliance_platform: 'ios',
          export_compliance_compliance_required: false,
          export_compliance_encryption_updated: false,
          export_compliance_app_type: nil,
          export_compliance_uses_encryption: true,
          export_compliance_is_exempt: true,
          export_compliance_contains_third_party_cryptography: true,
          export_compliance_contains_proprietary_cryptography: false,
          export_compliance_available_on_french_store: false
        }
    )
  end

  lane :beta do
    update_info_plist(
      plist_path: "meins/Info.plist",
      display_name: "meins"
    )
    build_app(
      workspace: "meins.xcworkspace",
      scheme: "meins"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: false,
      app_identifier: "com.matthiasn.meins"
    )
    deliver(
      force: true,
      skip_metadata: true,
      skip_screenshots: true,
      skip_binary_upload: true,
      submission_information: {
          export_compliance_platform: 'ios',
          export_compliance_compliance_required: false,
          export_compliance_encryption_updated: false,
          export_compliance_app_type: nil,
          export_compliance_uses_encryption: true,
          export_compliance_is_exempt: true,
          export_compliance_contains_third_party_cryptography: true,
          export_compliance_contains_proprietary_cryptography: false,
          export_compliance_available_on_french_store: false
        }
    )
  end
end
