import Base64 from "base-64";
import BuildMail from "buildmail";
//import CldrData from "cldr-data";
import CreateReactClass from "create-react-class";
import CryptoJs from "crypto-js";
import DraftJs from "draft-js";
import DraftJsExportHtml from "draft-js-export-html";
import DraftJsExportMarkdown from "draft-js-export-markdown";
import DraftJsLinkifyPlugin from "draft-js-linkify-plugin";
import DraftJsMentionPlugin from "draft-js-mention-plugin";
import DraftJsPluginsEditor from "draft-js-plugins-editor";
import DraftJsMdConverter  from "draftjs-md-converter";
import Electron from "electron";
import ElectronContextMenu from "electron-context-menu";
import ElectronFetch from "electron-fetch";
import ElectronLog from "electron-log";
import ElectronUpdater from "electron-updater";
import EmojiFlags from "emoji-flags";
import FindProcess from "find-process";
//import Globalize from "globalize";
import IanaTzData from "iana-tz-data";
import Imap from "imap";
import Immutable from "immutable";
import Install from "install";
import Leaflet from "leaflet";
import Lodash from "lodash";
import LodashThrottle from "lodash.throttle";
import MapboxGl from "mapbox-gl";
import Moment from "moment";
import MomentDurationFormat from "moment-duration-format";
import Quill from "quill";
import RandomColor from "randomcolor";
import React from "react";
import ReactDOM from "react-dom";
import ReactAddonsCssTransitionGroup from "react-addons-css-transition-group";
import ReactAddonsShallowCompare from "react-addons-shallow-compare";
import ReactBigCalendar from "react-big-calendar";
import ReactColor from "react-color";

import ReactEventTimeline from "react-event-timeline";
import ReactHorizontalTimeline from "react-horizontal-timeline";
import ReactInfiniteCalendar from "react-infinite-calendar";
import ReactList from "react-list";
import ReactResponsiveCarousel from "react-responsive-carousel";
import ReactWithDirection from "react-with-direction";
import Rome from "rome";
import ScreenshotDesktop from "screenshot-desktop";
import ShellEscape from "shell-escape";
import TcpPortUsed from "tcp-port-used";
import Tinicolor from "tinycolor";
import Tinicolor2 from "tinycolor2";
import Turndown from "turndown";
import WavesurferJs from "wavesurfer.js";

window.Base64 = Base64;
window.BuildMail = BuildMail;
//window.CldrData = CldrData;
window.CreateReactClass = CreateReactClass;
window.CryptoJs = CryptoJs;
window.DraftJs = DraftJs;
window.DraftJsExportHtml = DraftJsExportHtml;
window.DraftJsExportMarkdown = DraftJsExportMarkdown;
window.DraftJsLinkifyPlugin = DraftJsLinkifyPlugin;
window.DraftJsMentionPlugin = DraftJsMentionPlugin;
window.DraftJsPluginsEditor = DraftJsPluginsEditor;
window.DraftJsMdConverter = DraftJsMdConverter;
window.Electron = Electron;
window.ElectronContextMenu = ElectronContextMenu;
window.ElectronFetch = ElectronFetch;
window.ElectronLog = ElectronLog;
window.ElectronUpdater = ElectronUpdater;
window.EmojiFlags = EmojiFlags;
window.FindProcess = FindProcess;
window.IanaTzData = IanaTzData;
window.Imap = Imap;
window.Immutable = Immutable;
window.Install = Install;
window.Leaflet = Leaflet;
window.Lodash = Lodash;
window.LodashThrottle = LodashThrottle;
window.MapboxGl = MapboxGl;
window.Moment = Moment;
window.MomentDurationFormat = MomentDurationFormat;
window.Quill = Quill;
window.RandomColor = RandomColor;
window.React = React;
window.ReactDOM = ReactDOM;
window.ReactAddonsCssTransitionGroup = ReactAddonsCssTransitionGroup;
window.ReactAddonsShallowCompare = ReactAddonsShallowCompare;
window.ReactBigCalendar = ReactBigCalendar;
window.ReactColor = ReactColor;

window.ReactEventTimeline = ReactEventTimeline;
window.ReactHorizontalTimeline = ReactHorizontalTimeline;
window.ReactInfiniteCalendar = ReactInfiniteCalendar;
window.ReactList = ReactList;
window.ReactResponsiveCarousel = ReactResponsiveCarousel;
window.ReactWithDirection = ReactWithDirection;
window.Rome = Rome;
window.ScreenshotDesktop = ScreenshotDesktop;
window.ShellEscape = ShellEscape;
window.TcpPortUsed = TcpPortUsed;
window.Tinicolor = Tinicolor;
window.Tinicolor2 = Tinicolor2;
window.Turndown = Turndown;
window.WavesurferJs = WavesurferJs;

//window.Globalize = Globalize;
