{
  briefing(day: "%s") {
    day
    timestamp
    linked {
      timestamp
      tags
      perm_tags
      story {
        story_name
        timestamp
        saga {
          saga_name
          timestamp
        }
      }
      text
      md
      task {
        estimate_m
        points
        on_hold
        done
        priority
      }
    }
    comments {
      timestamp
      md
      latitude
      longitude
      completed_time
      comment_for
    }
  }

  started_tasks(pvt: %s) {
    timestamp
    md
    text
    story {
      timestamp
      story_name
      saga {
        timestamp
        saga_name
      }
    }
    task {
      estimate_m
      points
      on_hold
      done
      completed_s
      priority
    }

    comments {
      timestamp
      completed_time
      custom_fields
    }
  }

   waiting_habits(pvt: %s) {
     text
     timestamp
     habit
     story {
       story_name
       timestamp
       saga {
         saga_name
         timestamp
       }
     }
   }
}
