{
  briefing(day: "%s") {
    day
    timestamp
    linked {
      timestamp
      story {
        story_name
        timestamp
        linked_saga {
          saga_name
          timestamp
        }
      }
      text
      md
      task {
        estimate_m
        points
        on_hold
        done
        priority
      }
    }
    comments {
      timestamp
      md
      latitude
      longitude
      completed_time
    }
  }

  started_tasks {
    timestamp
    md
    text
    story {
      timestamp
      story_name
      linked_saga {
        timestamp
        saga_name
      }
    }
    task {
      estimate_m
      points
      on_hold
      done
      completed_s
      priority
    }
  }

   waiting_habits {
     text
     timestamp
     habit
     story {
       story_name
       timestamp
       linked_saga {
         saga_name
         timestamp
       }
     }
   }
}
