{
  day_stats(days: "%s", prio: 15) {
    day
    closed_tasks_cnt
    done_tasks_cnt
    entry_count
    tasks_cnt
    word_count
    total_time
    by_saga {
      logged
      saga {
        saga_name
        timestamp
      }
    }
    by_ts {
      timestamp
      comment_for
      completed
      manual
      summed
      story {
        story_name
        saga {
          saga_name
        }
      }
    }
  }
}