{
  habits_success(days: "%s") {
    completed {
      success
      day
      values {
        idx
        success
        v
      }
    }

    habit_entry {
      md
      timestamp
      habit
      story {
        story_name
      }
    }
  }
}
