{
  habits_success(days: "%s", pvt: "%s") {
    completed {
      success
      day
      values {
        idx
        success
        v
      }
    }

    habit_entry {
      md
      text
      timestamp
      habit
      story {
        story_name
        timestamp
      }
    }
  }
}
