{
  habits_success(day:"%s") {
    day
    habits {
      completed
      habit_entry {
        md
        text
        timestamp
        habit
        story {
          story_name
        }
      }
    }
  }
}