{
  started_tasks(pvt: %s, on_hold: %s) {
    timestamp
    md
    text
    story {
      timestamp
      story_name
      saga {
        timestamp
        saga_name
      }
    }
    task {
      estimate_m
      points
      on_hold
      done
      closed
      completed_s
      priority
    }

    comments {
      timestamp
      completed_time
      custom_fields
    }
  }
}
