// ignore_for_file: equal_keys_in_map
import 'package:flutter/material.dart';
import 'package:lotti/classes/config.dart';
import 'package:lotti/theme.dart';
import 'package:lotti/utils/color.dart';
import 'package:tinycolor2/tinycolor2.dart';

const defaultBaseColor = Color.fromRGBO(51, 77, 118, 1);
const brightBaseColor = Color.fromRGBO(244, 187, 41, 1);

final darkTheme = ColorConfig(
  entryBgColor: Colors.white,
  actionColor: const Color.fromRGBO(155, 200, 245, 1),
  tagColor: const Color.fromRGBO(155, 200, 246, 1),
  tagTextColor: const Color.fromRGBO(51, 51, 51, 1),
  personTagColor: const Color.fromRGBO(55, 201, 154, 1),
  storyTagColor: const Color.fromRGBO(200, 120, 0, 1),
  privateTagColor: Colors.red,
  bottomNavBackground: darken(defaultBaseColor, 10),
  bottomNavIconUnselected: const Color.fromRGBO(200, 195, 190, 1),
  bottomNavIconSelected: const Color.fromRGBO(252, 147, 76, 1),
  editorTextColor: const Color.fromRGBO(51, 51, 51, 1),
  starredGold: const Color.fromRGBO(255, 215, 0, 1),
  editorBgColor: Colors.white,
  baseColor: const Color.fromRGBO(51, 77, 118, 1),
  bodyBgColor: darken(defaultBaseColor, 20),
  headerBgColor: darken(defaultBaseColor, 10),
  entryCardColor: defaultBaseColor,
  entryTextColor: const Color.fromRGBO(200, 195, 190, 1),
  searchBgColor: const Color.fromRGBO(68, 68, 85, 0.3),
  appBarFgColor: const Color.fromRGBO(180, 190, 200, 1),
  codeBlockBackground: const Color.fromRGBO(228, 232, 240, 1),
  timeRecording: const Color.fromRGBO(255, 22, 22, 1),
  timeRecordingBg: const Color.fromRGBO(255, 44, 44, 0.95),
  outboxSuccessColor: const Color.fromRGBO(50, 120, 50, 1),
  outboxPendingColor: const Color.fromRGBO(200, 120, 0, 1),
  outboxErrorColor: const Color.fromRGBO(120, 50, 50, 1),
  headerFontColor: const Color.fromRGBO(155, 200, 245, 1),
  activeAudioControl: Colors.red,
  audioMeterBar: Colors.blue,
  audioMeterTooHotBar: Colors.orange,
  audioMeterPeakedBar: Colors.red,
  error: Colors.red,
  private: Colors.red,
  audioMeterBarBackground:
      TinyColor.fromColor(defaultBaseColor).lighten(30).color,
  inactiveAudioControl: const Color.fromRGBO(155, 155, 177, 1),
  unselectedChoiceChipTextColor: const Color.fromRGBO(51, 51, 51, 1),
  unselectedChoiceChipColor: const Color.fromRGBO(155, 155, 177, 1),
);

final brightTheme = ColorConfig(
  entryBgColor: Colors.white,
  actionColor: colorFromCssHex('#E27930'),
  tagColor: colorFromCssHex('#89BE2E'),
  tagTextColor: colorFromCssHex('#474B40'),
  personTagColor: const Color.fromRGBO(55, 201, 154, 1),
  storyTagColor: colorFromCssHex('#E27930'),
  privateTagColor: colorFromCssHex('#CF322F'),
  bottomNavBackground: darken(brightBaseColor, 10),
  bottomNavIconUnselected: colorFromCssHex('#474B40'),
  bottomNavIconSelected: Colors.white,
  editorTextColor: const Color.fromRGBO(51, 51, 51, 1),
  starredGold: const Color.fromRGBO(255, 215, 0, 1),
  editorBgColor: Colors.white,
  baseColor: const Color.fromRGBO(244, 187, 41, 1),
  bodyBgColor: darken(brightBaseColor, 20),
  headerBgColor: darken(brightBaseColor, 10),
  entryCardColor: brightBaseColor,
  entryTextColor: colorFromCssHex('#474B40'),
  searchBgColor: const Color.fromRGBO(68, 68, 85, 0.3),
  appBarFgColor: const Color.fromRGBO(180, 190, 200, 1),
  codeBlockBackground: const Color.fromRGBO(228, 232, 240, 1),
  timeRecording: colorFromCssHex('#CF322F'),
  timeRecordingBg: colorFromCssHex('#CF322FEE'),
  outboxSuccessColor: const Color.fromRGBO(50, 120, 50, 1),
  outboxPendingColor: const Color.fromRGBO(200, 120, 0, 1),
  outboxErrorColor: colorFromCssHex('#CF322F'),
  headerFontColor: const Color.fromRGBO(40, 60, 100, 1),
  activeAudioControl: colorFromCssHex('#CF322F'),
  audioMeterBar: Colors.blue,
  audioMeterTooHotBar: Colors.orange,
  audioMeterPeakedBar: colorFromCssHex('#CF322F'),
  error: colorFromCssHex('#CF322F'),
  private: colorFromCssHex('#CF322F'),
  audioMeterBarBackground:
      TinyColor.fromColor(defaultBaseColor).lighten(30).color,
  inactiveAudioControl: const Color.fromRGBO(155, 155, 177, 1),
  unselectedChoiceChipTextColor: const Color.fromRGBO(51, 51, 51, 1),
  unselectedChoiceChipColor: const Color.fromRGBO(155, 155, 177, 1),
);
