{
  briefing(day: "%s", prio: 12) {
    day
    timestamp
    linked {
      timestamp
      tags
      perm_tags
      story {
        story_name
        timestamp
        font_color
        badge_color
        pvt
        saga {
          saga_name
          timestamp
        }
      }
      text
      md
      task {
        estimate_m
        points
        on_hold
        closed
        closed_ts
        done
        priority
      }
    }
    comments {
      timestamp
      md
      entry_type
      latitude
      longitude
      completed_time
      comment_for
    }
  }
}
