{
  open_tasks(pvt: %s) {
    timestamp
    md
    tags
    story {
      timestamp
      story_name
      pvt
      font_color
      badge_color
      saga {
        timestamp
        saga_name
        pvt
      }
    }
    task {
      estimate_m
      points
      priority
    }
  }
}
