{
  started_tasks(pvt: %s) {
    timestamp
    md
    text
    last_saved

    story {
      timestamp
      story_name
      font_color
      badge_color
      pvt
      saga {
        timestamp
        saga_name
        pvt
      }
    }
    task {
      estimate_m
      points
      on_hold
      done
      closed
      closed_ts
      priority
    }

    comments {
      timestamp
      completed_time
      custom_fields
      last_saved
    }
  }
}
